### ISSUE TITLE
no attribute '_memory_usage'

### ISSUE THREAD

**Issue by kylerw** [ludeeus/custom_component_hadockermon#8]
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 316, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 223, in async_update_ha_state
    device_attr = self.device_state_attributes
  File "/config/custom_components/switch/hadockermon.py", line 119, in device_state_attributes
    ATTR_MEMORY: self._memory_usage,
AttributeError: 'ContainerSwitch' object has no attribute '_memory_usage'

**Comment by ludeeus** [comment]
I did a full rewrite of the component earlier today, can you try that and see if that soves the issue?
[https://github.com/HalfDecent/HA-Custom_components/tree/master/hadockermon](https://github.com/HalfDecent/HA-Custom_components/tree/master/hadockermon)

**Comment by kylerw** [comment]
Wow - great response on both issues I've submitted! Kudos!

It does appear to resolve it. I'll keep an eye on it to see if it resurfaces but I think you're rewrite did the trick.
